package run

import (
	"fmt"
	"strings"

	ai "github.com/jungju/jj/internal/openai"
)

func renderEvaluation(eval ai.EvaluationResult, spec, task string) string {
	ai.NormalizeEvaluation(&eval)
	var b strings.Builder
	b.WriteString("# EVAL\n\n")
	b.WriteString("## Summary\n\n")
	b.WriteString(redactSecrets(strings.TrimSpace(eval.Summary)))
	b.WriteString("\n\n")
	b.WriteString("## Result\n\n")
	b.WriteString(fmt.Sprintf("%s\n\n", eval.Result))
	b.WriteString("## Verdict\n\n")
	b.WriteString(fmt.Sprintf("%s\n\n", eval.Result))
	b.WriteString("## Score\n\n")
	b.WriteString(fmt.Sprintf("%d\n\n", eval.Score))
	writeList(&b, "Task Completion", nonEmptyList(eval.WhatChanged, "Evaluator did not report task completion details."))
	writeList(&b, "Verification Results", nonEmptyList(eval.TestCoverage, "Evaluator did not report verification results."))
	writeList(&b, "Diff Summary", nonEmptyList(eval.WhatChanged, "Evaluator did not report a diff summary."))
	writeList(&b, "Missing Tests", missingTests(eval))
	writeList(&b, "Next Actions", nextActions(eval.RecommendedFollowups))
	writeList(&b, "What Changed", eval.WhatChanged)
	writeList(&b, "SPEC Requirement Results", classifiedMarkdownItems(spec, eval, "Functional Requirements", "Acceptance Criteria"))
	writeList(&b, "TASK Item Results", classifiedMarkdownItems(task, eval, "Implementation Steps", "Required Changes", "Testing Requirements", "Done Criteria"))
	writeList(&b, "Requirements Coverage", eval.RequirementsCoverage)
	writeList(&b, "Test Coverage", eval.TestCoverage)
	writeList(&b, "Risks", eval.Risks)
	writeList(&b, "Unknowns", nil)
	writeList(&b, "Regressions", eval.Regressions)
	writeList(&b, "Recommended Follow-ups", eval.RecommendedFollowups)
	writeList(&b, "Secret Redaction Check", []string{"Generated evaluation content was redacted before being written."})
	return redactSecrets(b.String())
}

func renderDryRunEvaluation(runID, provider, plan, spec, task string) string {
	var b strings.Builder
	b.WriteString("# EVAL\n\n")
	b.WriteString("## Run Summary\n\n")
	b.WriteString(fmt.Sprintf("Run `%s` completed planning only using `%s`. Implementation was skipped because dry-run mode was enabled.\n\n", runID, provider))
	b.WriteString("## Result\n\n")
	b.WriteString("SKIPPED\n\n")
	b.WriteString("## Verdict\n\n")
	b.WriteString("SKIPPED\n\n")
	writeList(&b, "Task Completion", []string{"Planning completed; implementation was intentionally skipped."})
	writeList(&b, "Verification Results", []string{"Implementation verification was not run in dry-run mode."})
	writeList(&b, "Diff Summary", []string{"No workspace diff was generated by the dry run."})
	writeList(&b, "Missing Tests", []string{"Implementation tests were skipped in dry-run mode."})
	writeList(&b, "Next Actions", []string{"Review generated SPEC/TASK before running implementation."})
	writeList(&b, "Requirement Coverage", []string{
		"Plan was read and copied to input.md.",
		"Run-scoped docs/SPEC.md and docs/TASK.md were generated.",
		"Workspace docs and source files were not modified.",
	})
	writeList(&b, "Test Evidence", []string{"Implementation tests were skipped in dry-run mode."})
	writeList(&b, "Change Evidence", []string{"No implementation Codex run was invoked."})
	writeList(&b, "Risks", []string{"Generated SPEC/TASK still need human review before implementation."})
	writeList(&b, "Unknowns", []string{
		"Implementation behavior is unknown because no source changes were made.",
		fmt.Sprintf("Generated SPEC length: %d bytes; TASK length: %d bytes.", len(spec), len(task)),
	})
	writeList(&b, "Secret Redaction Check", []string{"Generated dry-run evaluation content was redacted before being written."})
	if strings.TrimSpace(plan) == "" {
		writeList(&b, "Plan Notes", []string{"Original plan content was empty after trimming."})
	}
	return redactSecrets(b.String())
}

func renderEvaluationFailure(err error, codexSummary, diffSummary string) string {
	var b strings.Builder
	b.WriteString("# EVAL\n\n")
	b.WriteString("## Run Summary\n\n")
	b.WriteString("Evaluation failed after implementation evidence was collected.\n\n")
	b.WriteString("## Result\n\n")
	b.WriteString("FAIL\n\n")
	b.WriteString("## Verdict\n\n")
	b.WriteString("FAIL\n\n")
	writeList(&b, "Task Completion", []string{"Unknown because evaluation failed."})
	writeList(&b, "Verification Results", []string{emptyFallback(codexSummary, "No Codex summary was available.")})
	writeList(&b, "Diff Summary", []string{emptyFallback(diffSummary, "No git diff summary was available.")})
	writeList(&b, "Missing Tests", []string{"Unknown because evaluation failed."})
	writeList(&b, "Next Actions", []string{"Review implementation, git diff, and evaluator failure manually."})
	writeList(&b, "Requirement Coverage", []string{"Unknown because the evaluator failed."})
	writeList(&b, "Test Evidence", []string{emptyFallback(codexSummary, "No Codex summary was available.")})
	writeList(&b, "Change Evidence", []string{emptyFallback(diffSummary, "No git diff summary was available.")})
	writeList(&b, "Risks", []string{"Evaluation failed and requires manual review."})
	writeList(&b, "Unknowns", []string{fmt.Sprintf("Evaluation error: %s", err)})
	writeList(&b, "Secret Redaction Check", []string{"Evaluation failure content was redacted before being written."})
	return redactSecrets(b.String())
}

func ensureSpecSections(spec, plan string) string {
	return ensureMarkdownSections(spec, "# SPEC", []string{
		"## Overview",
		"## Goals",
		"## Non-Goals",
		"## User Stories",
		"## Functional Requirements",
		"## CLI Behavior",
		"## Pipeline Behavior",
		"## Artifact Layout",
		"## Configuration",
		"## Error Handling",
		"## Security and Privacy",
		"## Observability",
		"## Acceptance Criteria",
	}, "Original plan reference:\n\n"+strings.TrimSpace(plan))
}

func ensureTaskSections(task, plan string) string {
	return ensureMarkdownSections(task, "# TASK", []string{
		"## Objective",
		"## Constraints",
		"## Implementation Steps",
		"## Files and Packages to Inspect",
		"## Required Changes",
		"## Testing Requirements",
		"## Manual Verification",
		"## Done Criteria",
	}, "Implement and verify the requested plan:\n\n"+strings.TrimSpace(plan))
}

func ensureMarkdownSections(markdown, title string, sections []string, fallback string) string {
	content := strings.TrimSpace(markdown)
	if content == "" {
		content = title + "\n\n" + fallback
	}
	if !strings.HasPrefix(content, title) {
		content = title + "\n\n" + content
	}
	for _, section := range sections {
		if !strings.Contains(content, section) {
			content += "\n\n" + section + "\n\nTBD based on the original plan and planner outputs."
		}
	}
	return content + "\n"
}

func writeList(b *strings.Builder, title string, items []string) {
	b.WriteString("## ")
	b.WriteString(title)
	b.WriteString("\n\n")
	if len(items) == 0 {
		b.WriteString("- (none)\n\n")
		return
	}
	for _, item := range items {
		b.WriteString("- ")
		b.WriteString(redactSecrets(strings.TrimSpace(item)))
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func emptyFallback(s, fallback string) string {
	if strings.TrimSpace(s) == "" {
		return fallback
	}
	return strings.TrimSpace(s)
}

func nonEmptyList(items []string, fallback string) []string {
	if len(items) == 0 {
		return []string{fallback}
	}
	return items
}

func nextActions(items []string) []string {
	if len(items) == 0 {
		return []string{"No follow-up actions were reported by evaluator."}
	}
	return items
}

func missingTests(eval ai.EvaluationResult) []string {
	for _, item := range eval.TestCoverage {
		lower := strings.ToLower(item)
		if strings.Contains(lower, "missing") || strings.Contains(lower, "not run") || strings.Contains(lower, "skipped") {
			return []string{item}
		}
	}
	return []string{"No missing tests were reported by evaluator."}
}

func classifiedMarkdownItems(markdown string, eval ai.EvaluationResult, sections ...string) []string {
	items := extractMarkdownSectionItems(markdown, sections...)
	if len(items) == 0 {
		return []string{"UNKNOWN: No explicit checklist items were found to classify. Evidence: docs/SPEC.md, docs/TASK.md, planning/evaluation.json."}
	}
	status := classificationStatus(eval)
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, fmt.Sprintf("%s: %s Evidence: docs/SPEC.md, docs/TASK.md, planning/evaluation.json, git/diff-summary.txt, codex/summary.md.", status, item))
	}
	return out
}

func classificationStatus(eval ai.EvaluationResult) string {
	if len(eval.Regressions) > 0 || eval.Result == "FAIL" {
		return "FAIL"
	}
	if eval.Result == "PASS" {
		return "PASS"
	}
	return "UNKNOWN"
}

func extractMarkdownSectionItems(markdown string, sectionNames ...string) []string {
	wanted := map[string]bool{}
	for _, name := range sectionNames {
		wanted[strings.ToLower(strings.TrimSpace(name))] = true
	}
	var out []string
	inWanted := false
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "## "):
			name := strings.TrimSpace(strings.TrimPrefix(trimmed, "## "))
			inWanted = wanted[strings.ToLower(name)]
			continue
		case strings.HasPrefix(trimmed, "#"):
			inWanted = false
			continue
		}
		if !inWanted {
			continue
		}
		if item := markdownListItem(trimmed); item != "" {
			out = append(out, item)
		}
	}
	if len(out) == 0 {
		for _, line := range strings.Split(markdown, "\n") {
			if item := markdownListItem(strings.TrimSpace(line)); item != "" {
				out = append(out, item)
			}
		}
	}
	return out
}

func markdownListItem(line string) string {
	line = strings.TrimSpace(line)
	for _, prefix := range []string{"- ", "* "} {
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix))
		}
	}
	for i, r := range line {
		if r < '0' || r > '9' {
			if i > 0 && (strings.HasPrefix(line[i:], ". ") || strings.HasPrefix(line[i:], ") ")) {
				return strings.TrimSpace(line[i+2:])
			}
			break
		}
	}
	return ""
}

func codexPrompt(specPath, taskPath string) string {
	return fmt.Sprintf(`You are running inside jj, a Go CLI that orchestrates planning, Codex implementation, tests, and evaluation.

Implement the work described by:
- %s
- %s

Requirements:
- Read both files before editing.
- Make the necessary code changes in this working tree.
- Choose and run the relevant tests yourself.
- Keep changes focused on the SPEC/TASK.
- In your final response, include changed files, tests run with results, and any remaining risks.
`, specPath, taskPath)
}
